# Generated by Django 5.0.3 on 2024-03-21 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=200)),
                ('caregiver_id', models.IntegerField(default=-1)),
                ('monitor_id', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=200)),
                ('sensor_type', models.CharField(max_length=200)),
                ('sensor_location', models.CharField(max_length=200)),
                ('device_model', models.CharField(max_length=200)),
                ('device_vendor', models.CharField(max_length=200)),
                ('accuracy', models.IntegerField(default=-1)),
                ('sensor_blind_duration', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=200)),
                ('event_type_enum', models.IntegerField(default=-1)),
                ('description', models.CharField(max_length=200)),
                ('advanced', models.CharField(max_length=200)),
                ('timestamp', models.IntegerField(default=-1)),
                ('start_time', models.IntegerField(default=-1)),
                ('end_time', models.IntegerField(default=-1)),
                ('length', models.IntegerField(default=-1)),
                ('value', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KitchenGuardServer.sensor')),
            ],
        ),
    ]
