# Generated by Django 5.0.3 on 2024-04-04 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenGuardServer', '0003_alter_event_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KitchenGuardServer.patient'),
        ),
    ]
